version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    networks: 
      - epd-rpi-network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000
      ZOOKEEPER_SYNC_LIMIT: 2
  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: kafka
    networks: 
      - epd-rpi-network
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: '-Xmx256M -Xms128M'
      KAFKA_ADVERTISED_HOST_NAME: kafka
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks: 
      - epd-rpi-network
    depends_on:
      - kafka
    ports:
      - 19000:9000
    profiles:
      - all
      - kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
  kafka-rest:
    image: confluentinc/cp-kafka-rest:7.3.0
    hostname: kafka-rest
    depends_on:
      - kafka
    networks: 
      - epd-rpi-network
    ports:
    - "8082:8082"
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_BOOTSTRAP_SERVERS: kafka:29092
  rpi_epd_controller:
    build: 
      context: .
      dockerfile: controller/Dockerfile
      args:
      - VITE_API_PORT=${VITE_API_PORT}
      - TIMEZONE=${TIMEZONE}
    depends_on:
      - kafka
    privileged: true
    networks: 
      - epd-rpi-network
    profiles:
      - all
      - controller
    ports:
      - ${VITE_API_PORT}:${VITE_API_PORT}
  rpi_epd_ui:
    build: 
      context: .
      dockerfile: front/Dockerfile
      args:
      - VITE_API_PORT=${VITE_API_PORT}
      - VITE_UI_PORT=${VITE_UI_PORT}
    networks: 
      - epd-rpi-network
    profiles:
      - all
      - ui
    ports:
      - ${VITE_UI_PORT}:${VITE_UI_PORT}
networks: 
  epd-rpi-network:
    driver: bridge
    external: true
    name: epd-rpi-network
